/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nexten_pi485_Pi485 */

#ifndef _Included_com_nexten_pi485_Pi485
#define _Included_com_nexten_pi485_Pi485
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nexten_pi485_Pi485
 * Method:    open
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_nexten_pi485_Pi485_open
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_nexten_pi485_Pi485
 * Method:    write
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_nexten_pi485_Pi485_write
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_nexten_pi485_Pi485
 * Method:    read
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_nexten_pi485_Pi485_read
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
