/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nexten_pi485_Pi485 */

#ifndef _Included_com_nexten_pi485_Pi485
#define _Included_com_nexten_pi485_Pi485
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nexten_pi485_Pi485
 * Method:    open
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_nexten_pi485_Pi485_open
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_nexten_pi485_Pi485
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nexten_pi485_Pi485_close
  (JNIEnv *, jobject);

/*
 * Class:     com_nexten_pi485_Pi485
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nexten_pi485_Pi485_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_nexten_pi485_Pi485
 * Method:    write
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_nexten_pi485_Pi485_write
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_nexten_pi485_Pi485
 * Method:    read
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_nexten_pi485_Pi485_read
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_nexten_pi485_Pi485
 * Method:    setPiVersion
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_nexten_pi485_Pi485_setPiVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nexten_pi485_Pi485
 * Method:    getPiVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nexten_pi485_Pi485_getPiVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_nexten_pi485_Pi485
 * Method:    getLibVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nexten_pi485_Pi485_getLibVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
